import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { Store } from "../utils/Store";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import {useSession} from 'next-auth/react'

export default function Layout({ children, title }) {
  const {status, data: session} = useSession()
  const { state } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);
  return (
    <>
      <Head>
        <title>{title ? title + " - Amazona" : "Amazona"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div className="flex flex-col min-h-screen justify-between">
        <header>
          <nav className="flex justify-between h-12 items-center shadow-md">
            <Link href="/">
              <a className="ml-2 text-lg font-bold">Amazona</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className="p-2">
                  Cart
                  {cartItemsCount > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                      {cartItemsCount}
                    </span>
                  )}
                </a>
              </Link>
              {status === 'loading' ? (
                'loading'
              ): session?.user ? (
               'Welcome '+ session.user.name
              ): (
                <Link href="/login">
                  <a className="p-2">Login</a>
                </Link>
              )

              }
              
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner ">
          <p>Copyright &copy; 2022 Amazona</p>
        </footer>
      </div>
    </>
  );
}
