import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirt",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirt",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirt",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pant",
      slug: "golf-pant",
      category: "Shirt",
      image: "/images/pants1.jpg",
      price: 100,
      brand: "Nike",
      rating: 4.2,
      numReviews: 9,
      countInStock: 10,
      description: "A popular shirt",
    },
    {
      name: "Track Pant",
      slug: "track-suit",
      category: "Shirt",
      image: "/images/pants2.jpg",
      price: 70,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Track Pant",
      slug: "track-suit",
      category: "Shirt",
      image: "/images/pants3.jpg",
      price: 70,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
  ],
};

export default data